engines:
  gofmt:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  golint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
      	  mass_threshold: 30
ratings:
  paths:
  - app/**
  - "**.go"
exclude_paths:
- spec/**/*
- "**/vendor/**/*"
