language: go

go:
  - 1.8
sudo: false

install:
  - go get -v ./...
  - go get -u github.com/golang/lint/golint

script:
  - for d in $(go list ./... | grep -v vendor); do go vet $d; done
  - for d in $(go list ./... | grep -v vendor); do golint $d; done
  - for d in $(go list ./... | grep -v vendor); do go test $d; done